---
# Detect OS and set package/service/log-dir variables
- name: Set Apache variables for Debian (Ubuntu)
  set_fact:
    apache_pkg: "apache2"
    apache_service: "apache2"
    apache_log_dir: "/var/log/apache2"
    apache_log_group: "adm"
  when: ansible_facts['os_family'] == "Debian"

- name: Set Apache variables for RedHat (Amazon Linux / CentOS)
  set_fact:
    apache_pkg: "httpd"
    apache_service: "httpd"
    apache_log_dir: "/var/log/httpd"
    apache_log_group: "root"
  when: ansible_facts['os_family'] == "RedHat"

# Fallback (if any other distro) - try httpd
- name: Set Apache variables for other OS (fallback)
  set_fact:
    apache_pkg: "httpd"
    apache_service: "httpd"
    apache_log_dir: "/var/log/httpd"
    apache_log_group: "root"
  when: apache_pkg is not defined

# Install package using appropriate package manager
- name: Install Apache (Ubuntu/Debian)
  apt:
    name: "{{ apache_pkg }}"
    state: present
    update_cache: yes
  when: ansible_facts['os_family'] == "Debian"

- name: Install Apache (RedHat/Amazon Linux)
  yum:
    name: "{{ apache_pkg }}"
    state: present
  when: ansible_facts['os_family'] == "RedHat"

- name: Ensure apache service is enabled and started
  systemd:
    name: "{{ apache_service }}"
    enabled: yes
    state: started

# Ensure log directory exists with appropriate permissions
- name: Ensure log directory exists
  file:
    path: "{{ apache_log_dir }}"
    state: directory
    owner: root
    group: "{{ apache_log_group | default('root') }}"
    mode: "0755"

# Optional: ensure default combined log format (safe no-op)
- name: Ensure combined LogFormat (create conf file if missing)
  copy:
    dest: "/etc/apache2/conf-available/logging.conf"
    content: |
      LogFormat "%h %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\"" combined
      CustomLog {{ apache_log_dir }}/access.log combined
  when: ansible_facts['os_family'] == "Debian"
  notify: Restart apache

- name: Ensure combined LogFormat for RedHat (create conf if missing)
  copy:
    dest: "/etc/httpd/conf.d/logging.conf"
    content: |
      LogFormat "%h %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\"" combined
      CustomLog {{ apache_log_dir }}/access.log combined
  when: ansible_facts['os_family'] == "RedHat"
  notify: Restart apache


