---
# 1️⃣ Create Loki user
- name: Create loki user
  user:
    name: loki
    system: yes
    shell: /sbin/nologin

# 2️⃣ Create Loki config directory
- name: Create Loki config directory
  file:
    path: /etc/loki
    state: directory
    owner: loki
    group: loki
    mode: '0755'

# 3️⃣ Create Loki base data directory
- name: Create Loki data directory
  file:
    path: /data/loki
    state: directory
    owner: loki
    group: loki
    mode: '0755'

# 4️⃣ Create Loki subdirectories (include compactor + wal)
- name: Create Loki subdirectories
  file:
    path: "/data/loki/{{ item }}"
    state: directory
    owner: loki
    group: loki
    mode: '0755'
  loop:
    - index
    - cache
    - chunks
    - wal
    - compactor   # 👈 fix for compactor module

# 5️⃣ Download Loki
- name: Download Loki
  get_url:
    url: "https://github.com/grafana/loki/releases/download/v2.9.6/loki-linux-amd64.zip"
    dest: /tmp/loki.zip

# 6️⃣ Extract Loki
- name: Extract Loki
  unarchive:
    src: /tmp/loki.zip
    dest: /usr/local/bin/
    remote_src: yes
    mode: '0755'

# 7️⃣ Loki config with compactor (permanent fix)
- name: Create Loki config
  copy:
    dest: /etc/loki/config.yml
    content: |
      auth_enabled: false

      server:
        http_listen_port: 3100
        grpc_listen_port: 9095

      ingester:
        wal:
          enabled: true
          dir: /data/loki/wal
        lifecycler:
          address: 127.0.0.1
          ring:
            kvstore:
              store: inmemory
            replication_factor: 1
          final_sleep: 0s
        chunk_idle_period: 5m
        chunk_retain_period: 30s
        max_transfer_retries: 0

      schema_config:
        configs:
          - from: 2020-10-24
            store: boltdb-shipper
            object_store: filesystem
            schema: v11
            index:
              prefix: index_
              period: 24h

      storage_config:
        boltdb_shipper:
          active_index_directory: /data/loki/index
          cache_location: /data/loki/cache
          shared_store: filesystem
        filesystem:
          directory: /data/loki/chunks

      compactor:                # 👈 permanent fix
        working_directory: /data/loki/compactor
        shared_store: filesystem

      limits_config:
        ingestion_rate_mb: 10
        ingestion_burst_size_mb: 20
        max_cache_freshness_per_query: 10m

      chunk_store_config:
        max_look_back_period: 0s

      table_manager:
        retention_deletes_enabled: true
        retention_period: 24h

# 8️⃣ Loki systemd service
- name: Create Loki systemd service
  copy:
    dest: /etc/systemd/system/loki.service
    content: |
      [Unit]
      Description=Loki
      After=network.target

      [Service]
      User=loki
      Group=loki
      ExecStart=/usr/local/bin/loki-linux-amd64 -config.file=/etc/loki/config.yml
      Restart=always

      [Install]
      WantedBy=multi-user.target

# 9️⃣ Start Loki service
- name: Start Loki service
  systemd:
    name: loki
    enabled: yes
    state: started

